### ISSUE TITLE
Already have it.

### ISSUE THREAD

**Issue by heavyuser** [neosmart/open#1]
its called start where do you think apple copy it from?

**Comment by mqudsi** [comment]
Hi @heavyuser 

That's not accessible from within other applications, it's as cmd.exe builtin.

**Comment by pyhedgehog** [comment]
Shouldn't this difference be noted in README? Maybe with usage examples?

**Comment by mqudsi** [comment]
@pyhedgehog would you like to submit a PR? I'll be happy to review and merge.
